alias ..='cd ..'
alias ...='cd ../..'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alhF --group-directories-first'
alias la='ls -a'
alias l='ls -GgahF --group-directories-first'
alias cpv='rsync -ah --info=progress2'

alias gs='git status'
alias gg='git log --all --graph'
alias gb='git branch'
alias gfo='git fetch origin'
